name: Publish Web Contest Sandbox

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: easy-peasy-robotics/web-contest-sandbox
        username: ${{ github.actor }}
        password: ${{ secrets.PUBLISH_DOCKER_IMAGE_TOKEN_PATTACINI }}
        workdir: dockerfiles/web-contest-sandbox
        registry: ghcr.io
        tags: "latest"
