name: Publish Web Contest Sandbox

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@main
      with:
        name: easy-peasy-robotics/web-contest-sandbox
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        workdir: dockerfiles/web-contest-sandbox
        registry: ghcr.io
        tags: "latest"
